name: n_back
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Binary dependencies resolved via conda to keep PsychoPy wheels fast and stable.
  - wxpython=4.2.*
  - numpy=1.26.*
  - scipy=1.12.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - pillow=10.*
  - pip>=23
  - setuptools
  - wheel
  # Install the project via pip so PsychoPy and marker packages come from pyproject.toml
  - pip:
      - -e .

